[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]
name = "nomad-simulation-parsers"
description = "A repository for housing NOMAD's collection of simulation parser plugins."
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Esma B. Boydas", email = "esma.boydas@physik.hu-berlin.de" },
    { name = "Nathan Daelman", email = "ndaelman@physik.hu-berlin.de" },
    { name = "Alvin N. Ladines", email = "ladinesa@physik.hu-berlin.de" },
    { name = "Bernadette Mohr", email = "mohrbern@physik.hu-berlin.de" },
    { name = "Joseph F. Rudzinski", email = "joseph.rudzinski@physik.hu-berlin.de" }
]
maintainers = [
    { name = "Nathan Daelman", email = "ndaelman@physik.hu-berlin.de" },
    { name = "Alvin N. Ladines", email = "ladinesa@physik.hu-berlin.de" },
    { name = "Joseph F. Rudzinski", email = "joseph.rudzinski@physik.hu-berlin.de" }
]
license = { file = "LICENSE" }
dependencies = [
    "nomad-lab>=1.3.16.dev100",
    "python-magic-bin; sys_platform == 'win32'",
    "phonopy>=2.35",
]

[project.urls]
Repository = "https://github.com/FAIRmat-NFDI/nomad-simulation-parsers"

[project.optional-dependencies]
dev = ["ruff", "pytest", "structlog"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

[tool.uv]
index-url = "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple"
build-constraint-dependencies = ["wheel<0.46"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # isort
    "I",
    # pylint
    "PL",
]

ignore = [
    "F403", # 'from module import *' used; unable to detect undefined names
]

fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# this is entirely optional, you can remove this if you wish to
[tool.ruff.format]
# use single quotes for strings.
quote-style = "single"

# indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ['PLR2004']

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]

[project.entry-points.'nomad.plugin']
abinit_parser = "nomad_simulation_parsers.parsers:abinit_parser"
abinit_schema_package = "nomad_simulation_parsers.schema_packages:abinit_schema_package"
ams_parser = "nomad_simulation_parsers.parsers:ams_parser"
ams_schema_package = "nomad_simulation_parsers.schema_packages:ams_schema_package"
crystal_parser = "nomad_simulation_parsers.parsers:crystal_parser"
crystal_schema_package = "nomad_simulation_parsers.schema_packages:crystal_schema_package"
exciting_parser = "nomad_simulation_parsers.parsers:exciting_parser"
exciting_schema_package = "nomad_simulation_parsers.schema_packages:exciting_schema_package"
fhiaims_parser = "nomad_simulation_parsers.parsers:fhiaims_parser"
fhiaims_schema_package = "nomad_simulation_parsers.schema_packages:fhiaims_schema_package"
gpaw_parser = "nomad_simulation_parsers.parsers:gpaw_parser"
gpaw_schema_package = "nomad_simulation_parsers.schema_packages:gpaw_schema_package"
octopus_parser = "nomad_simulation_parsers.parsers:octopus_parser"
octopus_schema_package = "nomad_simulation_parsers.schema_packages:octopus_schema_package"
phonopy_parser = "nomad_simulation_parsers.parsers:phonopy_parser"
phonopy_schema_package = "nomad_simulation_parsers.schema_packages:phonopy_schema_package"
quantumespresso_parser = "nomad_simulation_parsers.parsers:quantumespresso_parser"
quantumespresso_schema_package = "nomad_simulation_parsers.schema_packages:quantumespresso_schema_package"
vasp_parser = "nomad_simulation_parsers.parsers:vasp_parser"
vasp_schema_package = "nomad_simulation_parsers.schema_packages:vasp_schema_package"
wannier90_parser = "nomad_simulation_parsers.parsers:wannier90_parser"
wannier90_schema_package = "nomad_simulation_parsers.schema_packages:wannier90_schema_package"



[tool.cruft]
# Avoid updating workflow files, this leads to permissions issues
skip = [".github/*"]
